apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: your-dockerhub-username/hospital-system:latest
        command: ["node", "appointment-service.js"]
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  type: NodePort
  selector:
    app: appointment-service
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30081
