name: Terraform AWS Infrastructure Deployment

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for Terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1  # Set up Terraform

      - name: Terraform Init
        run: terraform init  # Initialize Terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan  # Plan the Terraform deployment

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan  # Apply the Terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Key
          AWS_DEFAULT_REGION: "us-east-1"  # Specify the AWS region (adjust as needed)
          
      - name: Terraform Validate
        run: terraform validate  # Validate Terraform configuration

      - name: Terraform Output
        run: terraform output  # Show Terraform outputs (e.g., IP addresses, resource names)
