name: Terraform AWS Infrastructure Deployment

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1  # Set up Terraform

      - name: Terraform Init
        run: terraform init  # Initialize Terraform
        working-directory: terraform  # Point to the terraform directory

      - name: Terraform Plan
        run: terraform plan -out=tfplan  # Create a Terraform plan
        working-directory: terraform  # Point to the terraform directory

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan  # Apply the Terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use AWS secrets from GitHub
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use AWS secrets from GitHub
          AWS_DEFAULT_REGION: "us-east-1"  # Specify the AWS region (change as necessary)
        working-directory: terraform  # Point to the terraform directory

      - name: Terraform Validate
        run: terraform validate  # Validate the Terraform configuration
        working-directory: terraform  # Point to the terraform directory

      - name: Terraform Output
        run: terraform output  # Show Terraform outputs after apply
        working-directory: terraform  # Point to the terraform directory
